### ISSUE TITLE
difference between msf_frame_to_msf() and time_frame_to_msf()

### ISSUE THREAD

**Issue by frgm** [lipnitsk/libcue#1]
What is the difference between [msf_frame_to_msf()](https://github.com/lipnitsk/libcue/blob/cbbde79f64042bef87f5c8b7661845525a04c97e/time.c#L17-L24) and [time_frame_to_msf()](https://github.com/lipnitsk/libcue/blob/cbbde79f64042bef87f5c8b7661845525a04c97e/time.c#L26-L33) ?

+
Where is time_mmssff_to_frame() (from [time.h](https://github.com/lipnitsk/libcue/blob/cbbde79f64042bef87f5c8b7661845525a04c97e/time.h#L13)) ?

**Comment by jotrk** [comment]
I'd say there's no difference. This happens when you have a really old code base. I'd suggest you remove the duplicate function and the extraneous declaration and see if it still compiles. I'd also suggest to remove the `msf_*` function, because the namespace prefix for time.h should be `time_`. :)

**Comment by lipnitsk** [comment]
@frgm, feel free to submit a PR cleaning this up. FYI, these functions are internal to the library and are not currently exported.

**Comment by frgm** [comment]
OK, here is [PR](https://github.com/lipnitsk/libcue/pull/2).

**Comment by frgm** [comment]
but those functions were exported in 1.4 version...

**Comment by lipnitsk** [comment]
True, pretty much everything was exported in 1.4 version for no good reason. From my point of view, libcue should only parse and provide read access to fields in a CUE file. From the next point onwards only functions declared in libcue.h will be exported.

**Comment by lipnitsk** [comment]
Fixed by merging #2
