### ISSUE TITLE
Please restore 1.4.0 release to sf.net page

### ISSUE THREAD

**Issue by jlindgren90** [lipnitsk/libcue#3]
The 1.4.0 release (libcue-1.4.0.tar.bz2) seems to have been deleted from the SourceForge page.  Please restore it as it's needed by downstream packaging (for example Arch Linux's makepkg system).

The URL should be:
http://downloads.sourceforge.net/libcue/libcue-1.4.0.tar.bz2

**Comment by jotrk** [comment]
Hi, please consider changing the package to use the releases from Github:

> https://github.com/lipnitsk/libcue/archive/v1.4.0.tar.gz

For Arch it's particularly easy, just change the URL in the PKGBUILD file. :)

There are several good reasons for moving away from sf.
Imho the most compelling reason is the distribution of malware.

**Comment by jlindgren90** [comment]
It would be nice to still provide the old GNU-style releases, which included the ./configure script.  The new GitHub-style "releases" don't appear to run autoconf/automake and thus ./configure is missing.

IMHO the best solution would be to upload the same .tar.bz2 that used to be on SourceForge to GitHub.  That way the checksum would still match as well, as one might expect from what is supposed to be the "same" release.

**Comment by jotrk** [comment]
Ah, I see! Github only generates tarballs from the tags.
That's unfortunate.
I think it should be possible to restore one of the older releases by checking out the tagged version. However, the checksum will very likely be different.
Anyhow, from what I can see, the next release is going to use cmake, so this needs to be changed anyway.

**Comment by jlindgren90** [comment]
Fedora has a copy of the old release here with a matching checksum, if that helps:
http://pkgs.fedoraproject.org/repo/pkgs/libcue/libcue-1.4.0.tar.bz2/5f5045f00e6ac92d9a057fe5b0982c69/libcue-1.4.0.tar.bz2

**Comment by lipnitsk** [comment]
Thanks for pointing this out, I have uploaded the above binary to https://github.com/lipnitsk/libcue/releases/download/v1.4.0/libcue-1.4.0.tar.bz2
Let me know if there is still a problem.
