### ISSUE TITLE
Please give library a proper soversion

### ISSUE THREAD

**Issue by nqn76** [lipnitsk/libcue#7]
The libcue library doesn't have a soversion set, so applications link directly to libcue.so.2.0.0. This means that distros have to recompile them for every patch release of libcue, even if there aren't any BIC changes. Please add a proper soversion to prevent this.

**Comment by lemenkov** [comment]
Sounds like distro-specific issue. I've just tested to be absolutely sure:

Auriga ~/work/libcue (git::master): ls -la  | grep libcue.so
lrwxrwxrwx.  1 petro petro    15 фев 24 13:45 libcue.so -> libcue.so.2.0.1
-rwxrwxr-x.  1 petro petro 60192 фев 24 13:45 libcue.so.2.0.1
Auriga ~/work/libcue (git::master):

**Comment by nqn76** [comment]
That's exactly the problem. There should be a libcue.so.x -> libcue.so.2.0.1 symlink, where x=soversion is only bumped on BIC releases.

**Comment by lipnitsk** [comment]
Fixed in 57ec834edffc8215cdb1c5ddff8934910b508da1 and re-released v2.0.1
